[package]
name = "test_analytics_rust"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
serde_json = "1.0"
ureq = { version = "2.9", features = ["json"] }
hostname = "0.4"
libc = "0.2"
